const algoritmo = [
    "O que é um algoritmo?",
    "o que é um algoritmo?",
    "O que é algoritmo?",
    "o que é algoritmo?",
    "O q é um algoritmo?",
    "o q é um algoritmo?",
    "O q é algoritmo?",
    "o q é algoritmo?",
    "O que e um algoritmo?",
    "o que e um algoritmo?",
    "O que e algoritmo?",
    "o que e algoritmo?",
    "O q e um algoritmo?",
    "o q e um algoritmo?",
    "O q e algoritmo?",
    "o q e algoritmo?",
    "O que é um algoritmo",
    "o que é um algoritmo",
    "O que é algoritmo",
    "o que é algoritmo",
    "O q é um algoritmo",
    "o q é um algoritmo",
    "O q é algoritmo",
    "o q é algoritmo",
    "O que e um algoritmo",
    "o que e um algoritmo",
    "O que e algoritmo",
    "o que e algoritmo",
    "O q e um algoritmo",
    "o q e um algoritmo",
    "O q e algoritmo",
    "o q e algoritmo",
    "Algoritmo",
    "algoritmo"
]

const italico = [
    "Como deixar a fonte em italico?",
    "como deixar a fonte em italico?",
    "Como deixar fonte em italico?",
    "como deixar fonte em italico?",
    "Como deixar fonte italico?",
    "como deixar fonte italico?",
    "Como deixar a fonte italico?",
    "como deixar a fonte italico?",
    "Como deixar a fonte em italico",
    "como deixar a fonte em italico",
    "Como deixar fonte em italico",
    "como deixar fonte em italico",
    "Como deixar fonte italico",
    "como deixar fonte italico",
    "Como deixar a fonte italico",
    "como deixar a fonte italico",
    "Deixar a fonte em italico",
    "deixar a fonte em italico",
    "Deixar fonte em italico",
    "deixar fonte em italico",
    "Deixar a fonte italico",
    "deixar a fonte italico",
    "Deixar fonte italico",
    "deixar fonte italico",
    "Fonte em italico",
    "fonte em italico",
    "Fonte italico",
    "fonte italico",
    "Italico",
    "italico"
]

const css = [
    "O que é CSS?",
    "o que é CSS?",
    "O que é Css?",
    "o que é Css?",
    "O que é css?",
    "o que é css?",
    "O que e CSS?",
    "o que e CSS?",
    "O que e Css?",
    "o que e Css?",
    "O que e css?",
    "o que e css?",
    "O q é CSS?",
    "o q é CSS?",
    "O q é Css?",
    "o q é Css?",
    "O q é css?",
    "o q é css?",
    "O q e CSS?",
    "o q e CSS?",
    "O q e Css?",
    "o q e Css?",
    "O q e css?",
    "o q e css?",
    "O que é CSS",
    "o que é CSS",
    "O que é Css",
    "o que é Css",
    "O que é css",
    "o que é css",
    "O que e CSS",
    "o que e CSS",
    "O que e Css",
    "o que e Css",
    "O que e css",
    "o que e css",
    "O q é CSS",
    "o q é CSS",
    "O q é Css",
    "o q é Css",
    "O q é css",
    "o q é css",
    "O q e CSS",
    "o q e CSS",
    "O q e Css",
    "o q e Css",
    "O q e css",
    "o q e css",
    "CSS",
    "Css",
    "css"
]

const opacidadeFundo = [
    "Como diminuir a opacidade do fundo do texto?",
    "como diminuir a opacidade do fundo do texto?",
    "Como diminuir opacidade do fundo do texto?",
    "como diminuir opacidade do fundo do texto?",
    "Como diminuir a opacidade de fundo do texto?",
    "como diminuir a opacidade de fundo do texto?",
    "Como diminuir opacidade de fundo do texto?",
    "como diminuir opacidade de fundo do texto?",
    "Como diminuir a opacidade do fundo do texto",
    "como diminuir a opacidade do fundo do texto",
    "Como diminuir opacidade do fundo do texto",
    "como diminuir opacidade do fundo do texto",
    "Como diminuir a opacidade de fundo do texto",
    "como diminuir a opacidade de fundo do texto",
    "Como diminuir opacidade de fundo do texto",
    "como diminuir opacidade de fundo do texto",
    "Diminuir a opacidade do fundo do texto",
    "diminuir a opacidade do fundo do texto",
    "Diminuir opacidade do fundo do texto",
    "diminuir opacidade do fundo do texto",
    "Diminuir a opacidade de fundo do texto",
    "diminuir a opacidade de fundo do texto",
    "Diminuir opacidade de fundo do texto",
    "diminuir opacidade de fundo do texto",
    "Diminuir opacidade fundo texto",
    "diminuir opacidade fundo texto",
    "Opacidade do fundo do texto",
    "opacidade do fundo do texto",
    "Opacidade de fundo do texto",
    "opacidade de fundo do texto",
    "Opacidade fundo texto",
    "opacidade fundo texto",
    "Opacidade fundo",
    "opacidade fundo"
]

const corFundo = [
    "Como mudar a cor do fundo do texto?",
    "como mudar a cor do fundo do texto?",
    "Como mudar a cor de fundo do texto?",
    "como mudar a cor de fundo do texto?",
    "Como mudar a cor de fundo?",
    "como mudar a cor de fundo?",
    "Como mudar a cor do fundo?",
    "como mudar a cor do fundo?",
    "Como mudar cor do fundo do texto?",
    "como mudar cor do fundo do texto?",
    "Como mudar cor de fundo do texto?",
    "como mudar cor de fundo do texto?",
    "Como mudar cor de fundo?",
    "como mudar cor de fundo?",
    "Como mudar cor do fundo?",
    "como mudar cor do fundo?",
    "Como mudar a cor do fundo do texto",
    "como mudar a cor do fundo do texto",
    "Como mudar a cor de fundo do texto",
    "como mudar a cor de fundo do texto",
    "Como mudar a cor de fundo",
    "como mudar a cor de fundo",
    "Como mudar a cor do fundo",
    "como mudar a cor do fundo",
    "Como mudar cor do fundo do texto",
    "como mudar cor do fundo do texto",
    "Como mudar cor de fundo do texto",
    "como mudar cor de fundo do texto",
    "Como mudar cor de fundo",
    "como mudar cor de fundo",
    "Como mudar cor do fundo",
    "como mudar cor do fundo",
    "Mudar a cor do fundo do texto",
    "mudar a cor do fundo do texto",
    "Mudar a cor de fundo do texto",
    "mudar a cor de fundo do texto",
    "Mudar a cor de fundo",
    "mudar a cor de fundo",
    "Mudar a cor do fundo",
    "mudar a cor do fundo",
    "Mudar cor do fundo do texto",
    "mudar cor do fundo do texto",
    "Mudar cor de fundo do texto",
    "mudar cor de fundo do texto",
    "Mudar cor de fundo",
    "mudar cor de fundo",
    "Mudar cor do fundo",
    "mudar cor do fundo",
    "Mudar cor fundo texto",
    "mudar cor fundo texto",
    "Mudar cor fundo",
    "mudar cor fundo"
]

const opacidadeTexto = [
    "Como diminuir opacidade do texto?",
    "como diminuir opacidade do texto?",
    "Como diminuir opacidade?",
    "como diminuir opacidade?",
    "Como diminuir opacidade texto?",
    "como diminuir opacidade texto?",
    "Como diminuir a opacidade do texto?",
    "como diminuir a opacidade do texto?",
    "Como diminuir a opacidade?",
    "como diminuir a opacidade?",
    "Como diminuir opacidade do texto",
    "como diminuir opacidade do texto",
    "Como diminuir opacidade",
    "como diminuir opacidade",
    "Diminuir opacidade do texto",
    "diminuir opacidade do texto",
    "Diminuir opacidade",
    "diminuir opacidade",
    "Como diminuir a opacidade do texto",
    "como diminuir a opacidade do texto",
    "Como diminuir a opacidade",
    "como diminuir a opacidade",
    "Diminuir a opacidade do texto",
    "diminuir a opacidade do texto",
    "Diminuir opacidade texto",
    "diminuir opacidade texto",
    "Diminuir a opacidade",
    "diminuir a opacidade",
    "Opacidade texto",
    "opacidade texto"
]

const linkarCss = [
    "Como linkar o CSS no HTML?",
    "como linkar o CSS no HTML?",
    "Como linkar CSS no HTML?",
    "como linkar CSS no HTML?",
    "Como linkar o css no html?",
    "como linkar o css no html?",
    "Como linkar css no html?",
    "como linkar css no html?",
    "Como linkar o CSS no html?",
    "como linkar o CSS no html?",
    "Como linkar o CSS no Html?",
    "como linkar o CSS no Html?",
    "Como linkar o Css no html?",
    "como linkar o Css no html?",
    "Como linkar o Css no Html?",
    "como linkar o Css no Html?",
    "Como linkar o css no Html?",
    "como linkar o css no Html?",
    "Como linkar CSS no html?",
    "como linkar CSS no html?",
    "Como linkar CSS no Html?",
    "como linkar CSS no Html?",
    "Como linkar Css no html?",
    "como linkar Css no html?",
    "Como linkar Css no Html?",
    "como linkar Css no Html?",
    "Como linkar css no Html?",
    "como linkar css no Html?",
    "Como linkar o CSS no HTML",
    "como linkar o CSS no HTML",
    "Como linkar CSS no HTML",
    "como linkar CSS no HTML",
    "Como linkar o css no html",
    "como linkar o css no html",
    "Como linkar css no html",
    "como linkar css no html",
    "Como linkar o CSS no html",
    "como linkar o CSS no html",
    "Como linkar o CSS no Html",
    "como linkar o CSS no Html",
    "Como linkar o Css no html",
    "como linkar o Css no html",
    "Como linkar o Css no Html",
    "como linkar o Css no Html",
    "Como linkar o css no Html",
    "como linkar o css no Html",
    "Como linkar CSS no html",
    "como linkar CSS no html",
    "Como linkar CSS no Html",
    "como linkar CSS no Html",
    "Como linkar Css no html",
    "como linkar Css no html",
    "Como linkar Css no Html",
    "como linkar Css no Html",
    "Como linkar css no Html",
    "como linkar css no Html",
    "Linkar CSS no HTML",
    "linkar CSS no HTML",
    "Linkar Css no HTML",
    "linkar Css no HTML",
    "Linkar css no HTML",
    "linkar css no HTML",
    "Linkar CSS no Html",
    "linkar CSS no Html",
    "Linkar Css no Html",
    "linkar Css no Html",
    "Linkar css no Html",
    "linkar css no Html",
    "Linkar CSS no html",
    "linkar CSS no html",
    "Linkar Css no html",
    "linkar Css no html",
    "Linkar css no html",
    "linkar css no html",
    "Linkar CSS",
    "linkar CSS",
    "Linkar Css",
    "linkar Css",
    "Linkar css",
    "linkar css",
    "Linkar o CSS no HTML",
    "linkar o CSS no HTML",
    "Linkar o Css no HTML",
    "linkar o Css no HTML",
    "Linkar o css no HTML",
    "linkar o css no HTML",
    "Linkar o CSS no Html",
    "linkar o CSS no Html",
    "Linkar o Css no Html",
    "linkar o Css no Html",
    "Linkar o css no Html",
    "linkar o css no Html",
    "Linkar o CSS no html",
    "linkar o CSS no html",
    "Linkar o Css no html",
    "linkar o Css no html",
    "Linkar o css no html",
    "linkar o css no html",
    "Linkar o CSS",
    "linkar o CSS",
    "Linkar o Css",
    "linkar o Css",
    "Linkar o css",
    "linkar o css"
]

const linkarJs = [
    "Como linkar o JavaScript no HTML?",
    "como linkar o JavaScript no HTML?",
    "Como linkar JavaScript no HTML?",
    "como linkar JavaScript no HTML?",
    "Como linkar o Javascript no HTML?",
    "como linkar o Javascript no HTML?",
    "Como linkar Javascript no HTML?",
    "como linkar Javascript no HTML?",
    "Como linkar o javascript no html?",
    "como linkar o javascript no html?",
    "Como linkar javascript no html?",
    "como linkar javascript no html?",
    "Como linkar o JavaScript no html?",
    "como linkar o JavaScript no html?",
    "Como linkar o JavaScript no Html?",
    "como linkar o JavaScript no Html?",
    "Como linkar o Javascript no html?",
    "como linkar o Javascript no html?",
    "Como linkar o Javascript no Html?",
    "como linkar o Javascript no Html?",
    "Como linkar o javascript no Html?",
    "como linkar o javascript no Html?",
    "Como linkar JavaScript no html?",
    "como linkar JavaScript no html?",
    "Como linkar JavaScript no Html?",
    "como linkar JavaScript no Html?",
    "Como linkar Javascript no html?",
    "como linkar Javascript no html?",
    "Como linkar Javascript no Html?",
    "como linkar Javascript no Html?",
    "Como linkar javascript no Html?",
    "como linkar javascript no Html?",
    "Como linkar o Js no HTML?",
    "como linkar o Js no HTML?",
    "Como linkar Js no HTML?",
    "como linkar Js no HTML?",
    "Como linkar o js no HTML?",
    "como linkar o js no HTML?",
    "Como linkar js no HTML?",
    "como linkar js no HTML?",
    "Como linkar o Js no html?",
    "como linkar o Js no html?",
    "Como linkar Js no html?",
    "como linkar Js no html?",
    "Como linkar o js no html?",
    "como linkar o js no html?",
    "Como linkar o Js no Html?",
    "como linkar o Js no Html?",
    "Como linkar o js no Html?",
    "como linkar o js no Html?",
    "Como linkar js no html?",
    "como linkar js no html?",
    "Como linkar Js no Html?",
    "como linkar Js no Html?",
    "Como linkar js no Html?",
    "como linkar js no Html?",
    "Como linkar o JavaScript no HTML",
    "como linkar o JavaScript no HTML",
    "Como linkar JavaScript no HTML",
    "como linkar JavaScript no HTML",
    "Como linkar o javascript no html",
    "como linkar o javascript no html",
    "Como linkar javascript no html",
    "como linkar javascript no html",
    "Como linkar o JavaScript no html",
    "como linkar o JavaScript no html",
    "Como linkar o JavaScript no Html",
    "como linkar o JavaScript no Html",
    "Como linkar o Javascript no html",
    "como linkar o Javascript no html",
    "Como linkar o Javascript no Html",
    "como linkar o Javascript no Html",
    "Como linkar o javascript no Html",
    "como linkar o javascript no Html",
    "Como linkar JavaScript no html",
    "como linkar JavaScript no html",
    "Como linkar JavaScript no Html",
    "como linkar JavaScript no Html",
    "Como linkar Javascript no html",
    "como linkar Javascript no html",
    "Como linkar Javascript no Html",
    "como linkar Javascript no Html",
    "Como linkar javascript no Html",
    "como linkar javascript no Html",
    "Como linkar o Js no HTML",
    "como linkar o Js no HTML",
    "Como linkar Js no HTML",
    "como linkar Js no HTML",
    "Como linkar o js no HTML",
    "como linkar o js no HTML",
    "Como linkar js no HTML",
    "como linkar js no HTML",
    "Como linkar o Js no html",
    "como linkar o Js no html",
    "Como linkar Js no html",
    "como linkar Js no html",
    "Como linkar o js no html",
    "como linkar o js no html",
    "Como linkar o Js no Html",
    "como linkar o Js no Html",
    "Como linkar o js no Html",
    "como linkar o js no Html",
    "Como linkar js no html",
    "como linkar js no html",
    "Como linkar Js no Html",
    "como linkar Js no Html",
    "Como linkar js no Html",
    "como linkar js no Html",
    "Linkar JavaScript no HTML",
    "linkar JavaScript no HTML",
    "Linkar Javascript no HTML",
    "linkar Javascript no HTML",
    "Linkar javascript no HTML",
    "linkar javascript no HTML",
    "Linkar JavaScript no Html",
    "linkar JavaScript no Html",
    "Linkar Javascript no Html",
    "linkar Javascript no Html",
    "Linkar javascript no Html",
    "linkar javascript no Html",
    "Linkar JavaScript no html",
    "linkar JavaScript no html",
    "Linkar Javascript no html",
    "linkar Javascript no html",
    "Linkar javascript no html",
    "linkar javascript no html",
    "Linkar JavaScript",
    "linkar JavaScript",
    "Linkar Javascript",
    "linkar Javascript",
    "Linkar javascript",
    "linkar javascript",
    "Linkar o JavaScript no HTML",
    "linkar o JavaScript no HTML",
    "Linkar o Javascript no HTML",
    "linkar o Javascript no HTML",
    "Linkar o javascript no HTML",
    "linkar o javascript no HTML",
    "Linkar o JavaScript no Html",
    "linkar o JavaScript no Html",
    "Linkar o Javascript no Html",
    "linkar o Javascript no Html",
    "Linkar o javascript no Html",
    "linkar o javascript no Html",
    "Linkar o JavaScript no html",
    "linkar o JavaScript no html",
    "Linkar o Javascript no html",
    "linkar o Javascript no html",
    "Linkar o javascript no html",
    "linkar o javascript no html",
    "Linkar o JavaScript",
    "linkar o JavaScript",
    "Linkar o Javascript",
    "linkar o Javascript",
    "Linkar o javascript",
    "linkar o javascript",
    "Linkar o Js no HTML",
    "linkar o Js no HTML",
    "Linkar Js no HTML",
    "linkar Js no HTML",
    "Linkar o js no HTML",
    "linkar o js no HTML",
    "Linkar js no HTML",
    "linkar js no HTML",
    "Linkar o Js no html",
    "linkar o Js no html",
    "Linkar Js no html",
    "linkar Js no html",
    "Linkar o js no html",
    "linkar o js no html",
    "Linkar o Js no Html",
    "linkar o Js no Html",
    "Linkar o js no Html",
    "linkar o js no Html",
    "Linkar js no html",
    "linkar js no html",
    "Linkar Js no Html",
    "linkar Js no Html",
    "Linkar js no Html",
    "linkar js no Html"
]

const classe = [
    "O que é uma Class?",
    "o que é uma Class?",
    "O que é uma class?",
    "o que é uma class?",
    "O que e uma Class?",
    "o que e uma Class?",
    "O que e uma class?",
    "o que e uma class?",
    "O que é Class?",
    "o que é Class?",
    "O que é class?",
    "o que é class?",
    "O que e Class?",
    "o que e Class?",
    "O que e class?",
    "o que e class?",
    "O q é uma Class?",
    "o q é uma Class?",
    "O q é uma class?",
    "o q é uma class?",
    "O q e uma Class?",
    "o q e uma Class?",
    "O q e uma class?",
    "o q e uma class?",
    "O q é Class?",
    "o q é Class?",
    "O q é class?",
    "o q é class?",
    "O q e Class?",
    "o q e Class?",
    "O q e class?",
    "o q e class?",
    "O que é uma Class",
    "o que é uma Class",
    "O que é uma class",
    "o que é uma class",
    "O que e uma Class",
    "o que e uma Class",
    "O que e uma class",
    "o que e uma class",
    "O que é Class",
    "o que é Class",
    "O que é class",
    "o que é class",
    "O que e Class",
    "o que e Class",
    "O que e class",
    "o que e class",
    "O q é uma Class",
    "o q é uma Class",
    "O q é uma class",
    "o q é uma class",
    "O q e uma Class",
    "o q e uma Class",
    "O q e uma class",
    "o q e uma class",
    "O q é Class",
    "o q é Class",
    "O q é class",
    "o q é class",
    "O q e Class",
    "o q e Class",
    "O q e class",
    "o q e class",
    "Class",
    "class"
]

const ids = [
    "O que é um Id?",
    "o que é um Id?",
    "O que é um id?",
    "o que é um id?",
    "O que e um Id?",
    "o que e um Id?",
    "O que e um id?",
    "o que e um id?",
    "O que é Id?",
    "o que é Id?",
    "O que é id?",
    "o que é id?",
    "O que e Id?",
    "o que e Id?",
    "O que e id?",
    "o que e id?",
    "O q é um Id?",
    "o q é um Id?",
    "O q é um id?",
    "o q é um id?",
    "O q e um Id?",
    "o q e um Id?",
    "O q e um id?",
    "o q e um id?",
    "O q é Id?",
    "o q é Id?",
    "O q é id?",
    "o q é id?",
    "O q e Id?",
    "o q e Id?",
    "O q e id?",
    "o q e id?",
    "O que é um Id",
    "o que é um Id",
    "O que é um id",
    "o que é um id",
    "O que e um Id",
    "o que e um Id",
    "O que e um id",
    "o que e um id",
    "O que é Id",
    "o que é Id",
    "O que é id",
    "o que é id",
    "O que e Id",
    "o que e Id",
    "O que e id",
    "o que e id",
    "O q é um Id",
    "o q é um Id",
    "O q é um id",
    "o q é um id",
    "O q e um Id",
    "o q e um Id",
    "O q e um id",
    "o q e um id",
    "O q é Id",
    "o q é Id",
    "O q é id",
    "o q é id",
    "O q e Id",
    "o q e Id",
    "O q e id",
    "o q e id",
    "Id",
    "id"
]

const classId = [
    "Qual a diferença entre Class e Id?",
    "qual a diferença entre Class e Id?",
    "Qual a diferença entre class e Id?",
    "qual a diferença entre class e Id?",
    "Qual a diferença entre Class e id?",
    "qual a diferença entre Class e id?",
    "Qual a diferença entre class e id?",
    "qual a diferença entre class e id?",
    "Qual diferença entre Class e Id?",
    "qual diferença entre Class e Id?",
    "Qual diferença entre class e Id?",
    "qual diferença entre class e Id?",
    "Qual diferença entre Class e id?",
    "qual diferença entre Class e id?",
    "Qual diferença entre class e id?",
    "qual diferença entre class e id?",
    "Qual a diferença de Class e Id?",
    "qual a diferença de Class e Id?",
    "Qual a diferença de class e Id?",
    "qual a diferença de class e Id?",
    "Qual a diferença de Class e id?",
    "qual a diferença de Class e id?",
    "Qual a diferença de class e id?",
    "qual a diferença de class e id?",
    "Qual diferença de Class e Id?",
    "qual diferença de Class e Id?",
    "Qual diferença de class e Id?",
    "qual diferença de class e Id?",
    "Qual diferença de Class e id?",
    "qual diferença de Class e id?",
    "Qual diferença de class e id?",
    "qual diferença de class e id?",
    "Qual a diferença entre Class e Id",
    "qual a diferença entre Class e Id",
    "Qual a diferença entre class e Id",
    "qual a diferença entre class e Id",
    "Qual a diferença entre Class e id",
    "qual a diferença entre Class e id",
    "Qual a diferença entre class e id",
    "qual a diferença entre class e id",
    "Qual diferença entre Class e Id",
    "qual diferença entre Class e Id",
    "Qual diferença entre class e Id",
    "qual diferença entre class e Id",
    "Qual diferença entre Class e id",
    "qual diferença entre Class e id",
    "Qual diferença entre class e id",
    "qual diferença entre class e id",
    "Qual a diferença de Class e Id",
    "qual a diferença de Class e Id",
    "Qual a diferença de class e Id",
    "qual a diferença de class e Id",
    "Qual a diferença de Class e id",
    "qual a diferença de Class e id",
    "Qual a diferença de class e id",
    "qual a diferença de class e id",
    "Qual diferença de Class e Id",
    "qual diferença de Class e Id",
    "Qual diferença de class e Id",
    "qual diferença de class e Id",
    "Qual diferença de Class e id",
    "qual diferença de Class e id",
    "Qual diferença de class e id",
    "qual diferença de class e id",
    "Diferença entre Class e Id",
    "diferença entre Class e Id",
    "Diferença entre class e Id",
    "diferença entre class e Id",
    "Diferença entre Class e id",
    "diferença entre Class e id",
    "Diferença entre class e id",
    "diferença entre class e id",
    "Diferença de Class e Id",
    "diferença de Class e Id",
    "Diferença de class e Id",
    "diferença de class e Id",
    "Diferença de Class e id",
    "diferença de Class e id",
    "Diferença de class e id",
    "diferença de class e id",
    "Diferença Class e Id",
    "diferença Class e Id",
    "Diferença class e Id",
    "diferença class e Id",
    "Diferença Class e id",
    "diferença Class e id",
    "Diferença class e id",
    "diferença class e id",
    "Class e Id",
    "class e Id",
    "Class e id",
    "class e id",
    "Class Id",
    "class Id",
    "Class id",
    "class id"
]

const html = [
    "O que é HTML?",
    "o que é HTML?",
    "O que é Html?",
    "o que é Html?",
    "O que é html?",
    "o que é html?",
    "O que e HTML?",
    "o que e HTML?",
    "O que e Html?",
    "o que e Html?",
    "O que e html?",
    "o que e html?",
    "O q é HTML?",
    "o q é HTML?",
    "O q é Html?",
    "o q é Html?",
    "O q é html?",
    "o q é html?",
    "O q e HTML?",
    "o q e HTML?",
    "O q e Html?",
    "o q e Html?",
    "O q e html?",
    "o q e html?",
    "O que é HTML",
    "o que é HTML",
    "O que é Html",
    "o que é Html",
    "O que é html",
    "o que é html",
    "O que e HTML",
    "o que e HTML",
    "O que e Html",
    "o que e Html",
    "O que e html",
    "o que e html",
    "O q é HTML",
    "o q é HTML",
    "O q é Html",
    "o q é Html",
    "O q é html",
    "o q é html",
    "O q e HTML",
    "o q e HTML",
    "O q e Html",
    "o q e Html",
    "O q e html",
    "o q e html",
    "HTML",
    "Html",
    "html"
]

