const respostas = [
    "Resposta não consta",
    "Um algoritmo é simplesmente uma série de instruções a serem seguidas para resolver um problema.",
    "E quando que devem ser criados? Sempre que queremos montar uma sequência de passos necessários para solucionar um problema.",
    "tag < em >, tag < i > ou font-style: italic;",
    "Cascading Style Sheets (Folha de Estilo em Cascata) é usado para estilizar elementos escritos em uma linguagem de marcação como HTML. O CSS separa o conteúdo da representação visual do site. Pense na decoração da sua página. Utilizando o CSS é possível alterar a cor do texto e do fundo, fonte e espaçamento entre parágrafos. Também pode criar tabelas, usar variações de layouts, ajustar imagens para suas respectivas telas e assim por diante.",
    "Para mudar propriedades de texto como a cor do fundo no CSS utilizaremos o background-color, e o valor que ela precisa é de uma cor, que pode ser o nome da cor em inglês como red ou um hexadecimal como #000000 (que representa a cor preta).",
    "Mas para diminuir a opacidade do fundo do texto, utilizando o formato rgba deverá funcionar: background-color: rgba(10, 23, 55, 0.5); onde 0.5 é o nível de opacidade, que vai de 0 a 1 onde o valor 0 indica um elemento completamente transparente e o valor 1 completamente opaco.",
    "Para alterar a opacidade de um elemento, basta atribuir um valor entre 0 e 1 à propriedade, opacity. Neste caso, o valor 0 indica um elemento completamente transparente, enquanto o valor 1 torna o elemento totalmente opaco. Ex.: opacity: 0.6",
    "< head > < link rel=''stylesheet'' type=''text/css'' href=''stylesheet.css'' media=''screen'' /> < /head >",
    "Certifique de informar o caminho correto do CSS no href. É recomendada que o arquivo CSS esteja no mesmo diretório do arquivo HTML ou que seja criado um subdiretório chamado CSS para armazenar os arquivos (se os arquivos forem armazenados no diretório CSS, o href deve ser mudado para href=”CSS/stylesheet.css” no exemplo acima).",
    "< head > < script type=”text/javascript” src=”script.js” defer > < /script > < /head >",
    "Ou < body > < script src=”script.js” > < /script > < /body > Certificando de informar o caminho correto do JavaScript no src.",
    "As classes são uma forma de identificar um grupo de elementos. Através delas, pode-se atribuir formatação a VÁRIOS elementos de uma vez.",
    "Então se tiverem várias 'divs' com a class=classe1 e você coloca background-color: blue na classe1, todas as 'divs' que estiverem com a class “classe1” estarão com um background azul (blue).",
    "Os ids são uma forma de identificar um elemento, e dever ser ÚNICAS para cada elemento. É como se fossem impressões digitais de nossos dedos ou RGs. Através delas, pode-se atribuir formatação a um elemento em especial. Então não podemos repetir um 'id'. Deve ser especialmente única para cada elemento.",
    "Hyper Text Markup Lenguage (Linguagem de Marcação de Hipertexto), trata-se de uma linguagem de marcação para desenvolver páginas e documentos eletrônicos para a internet, fornecendo informações para usuários, navegadores e mecanismos de busca.",
    "Também é importante entender que ele não é uma linguagem de programação, já que seu objetivo não é criar um software, e, sim, marcar a estrutura de linguagens de programação de fato, como o JavaScript. Ou seja, ele indica onde os elementos aparecerão na aplicação. Ainda assim, de maneira similar a linguagens de programação, ele possui sintaxe e palavras reservadas.",
    "",
]